apiVersion: v1
kind: ConfigMap
metadata:
  name: liquibase-config
data:
  LIQUIBASE_CHANGELOG: "/liquibase/init.sql"  # Обновлено с ./init.sql на абсолютный путь в контейнере
  LIQUIBASE_URL: "jdbc:postgresql://192.168.1.181:5432/postgres"
  LIQUIBASE_USER: "postgres"
  LIQUIBASE_PASSWORD: "postgres"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: liquibase-nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: liquibase-nginx
  template:
    metadata:
      labels:
        app: liquibase-nginx
    spec:
      initContainers:
        - name: liquibase-init
          image: liquibase/liquibase:latest
          env:
            - name: LIQUIBASE_CHANGELOG
              valueFrom:
                configMapKeyRef:
                  name: liquibase-config
                  key: LIQUIBASE_CHANGELOG
            - name: LIQUIBASE_URL
              valueFrom:
                configMapKeyRef:
                  name: liquibase-config
                  key: LIQUIBASE_URL
            - name: LIQUIBASE_USER
              valueFrom:
                configMapKeyRef:
                  name: liquibase-config
                  key: LIQUIBASE_USER
            - name: LIQUIBASE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: liquibase-config
                  key: LIQUIBASE_PASSWORD
          command:
            - "sh"
            - "-c"
            - >
              liquibase update
              --changeLogFile=${LIQUIBASE_CHANGELOG} 
              --url=${LIQUIBASE_URL} 
              --username=${LIQUIBASE_USER} 
              --password=${LIQUIBASE_PASSWORD}
          volumeMounts:
            - name: changelog-volume
              mountPath: /liquibase  # Убедитесь, что этот путь совпадает с тем, где хранится init.sql

      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80  # Порт для Nginx
          volumeMounts:
            - name: changelog-volume
              mountPath: /usr/share/nginx/html  # Указываем путь, где Nginx будет искать файлы

      volumes:
        - name: changelog-volume
          hostPath:
            path: /mnt/c/Users/user/IdeaProjects/GitLbase/src/main/resources/db/sqlMigration  # Локальный путь к файлам